apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hello-deployment
  name: hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hello-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-deployment
    spec:
      containers:
      - image: localhost:32000/nodejs-hello-world:1.0.0
        name: hello-deployment
        ports:
        - containerPort: 3000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources: {}
status: {}
