apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  ports:
  - port: 3000
    nodePort: 31000
    protocol: TCP
    targetPort: 3000
  selector:
    run: hello
  type: NodePort
status:
  loadBalancer: {}
