apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: localhost:32000/nodejs-hello-world:1.0.0
    name: hello
    ports:
    - containerPort: 3000
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
