apiVersion: v1
kind: Pod
metadata:
  labels:
    run: two-containers
  name: two-containers
spec:

  volumes:
    - name: shared-volume
      emptyDir: {}

  containers:
  - image: nginx
    name: nginx-containers
    ports:
    - containerPort: 80
    volumeMounts:
      - name: shared-volume
        mountPath: /usr/share/nginx/html

  - image: debian
    name: debian-container
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /pod-data/index.html; sleep 1; done;"]
    volumeMounts:
      - name: shared-volume
        mountPath: /pod-data
